### ISSUE TITLE
Could you share the train code?

### ISSUE THREAD

**Issue by ChrisLLLLL** [yosungho/LineTR#6]
Thank you for your work! Could you share the train code?

**Comment by yosungho** [comment]
Hi Chris, The training code isn't ready to be shared. To create the training code, I referred to SuperPoint and SuperGlue and there are several training codes that we can utilize (e.g. LoFTR, D2-Net, etc.). Please consider making a line version of them.

**Comment by ChrisLLLLL** [comment]
ok,Thank you for your answer

**Comment by ChrisLLLLL** [comment]
Hello, my scientific research has reached a crisis period, my thesis has not been progressing, I intend to make some changes on your basis to use. I had to come to you again for training code. my mail address is 690376582@qq.com. I really beg if you can send me a training code. I promise to use it only for myself.

**Comment by ChrisLLLLL** [comment]
> Hi Chris, The training code isn't ready to be shared. To create the training code, I referred to SuperPoint and SuperGlue and there are several training codes that we can utilize (e.g. LoFTR, D2-Net, etc.). Please consider making a line version of them.
I tried to change the training code with reference to superglue and superpoint, but my ability did not get the results I wanted, I had to come to you as a last resort.

**Comment by yosungho** [comment]
> Hello, my scientific research has reached a crisis period, my thesis has not been progressing, I intend to make some changes on your basis to use. I had to come to you again for training code. my mail address is [690376582@qq.com](mailto:690376582@qq.com). I really beg if you can send me a training code. I promise to use it only for myself.

Hi Chris. Okay, I will share the training code for homography augmentation within a few days. However, the ScanNet training code is not going to be opened since it is unorganized.

**Comment by Zhuyawen7** [comment]
> > Hello, my scientific research has reached a crisis period, my thesis has not been progressing, I intend to make some changes on your basis to use. I had to come to you again for training code. my mail address is [690376582@qq.com](mailto:690376582@qq.com). I really beg if you can send me a training code. I promise to use it only for myself.
> 
> Hi Chris. Okay, I will share the training code for homography augmentation within a few days. However, the ScanNet training code is not going to be opened since it is unorganized.

Thank you very much! 
It's a pity that you can't give me a reference for training scannet, I can't solve the problem of how to train the line features on the scannet and get a weight like "lineTR_weight.pth", do you have any suggestions? Do you think I will get a good result if I train on the wireframe dataset?

**Comment by ChrisLLLLL** [comment]
> > Hello, my scientific research has reached a crisis period, my thesis has not been progressing, I intend to make some changes on your basis to use. I had to come to you again for training code. my mail address is [690376582@qq.com](mailto:690376582@qq.com). I really beg if you can send me a training code. I promise to use it only for myself.
> 
> Hi Chris. Okay, I will share the training code for homography augmentation within a few days. However, the ScanNet training code is not going to be opened since it is unorganized.

Thank you very much!
It's a pity that you can't give me a reference for training scannet, I can't solve the problem of how to train the line features on the scannet and get a weight like "lineTR_weight.pth", do you have any suggestions? Do you think I will get a good result if I train on the wireframe dataset?

**Comment by ChrisLLLLL** [comment]
Thanks again, I read your paper again, I think by learning your code I will be able to know how to  establish ground-truth line correspondences from an image pair. and use it to train. If you send it in two days, it will be very helpful to me.
Thank you for taking the time to check and reply to my question. Best wishes to you!

**Comment by ChrisLLLLL** [comment]
Hello,
I haven't received your email yet, when do you plan to send it？
In the past two days, I have tried to write the training code, but I have encountered difficulties in solving the loss and groundtruth, I hope to get your help.
Looking forward to your reply.

**Comment by yosungho** [comment]
Chris, I will upload the base training code this weekend.

**Comment by ChrisLLLLL** [comment]
I'm sorry for the trouble my anxiety has caused you, thank you again for your efforts

**Comment by yosungho** [comment]
Hi Chris. As I mentioned, I upload the training code. You may need storage for the dataset files. Please have a try. :)

**Comment by yosungho** [comment]
> I'm sorry for the trouble my anxiety has caused you, thank you again for your efforts

Hi Chris. As I mentioned, I upload the training code. You may need storage for the dataset files. Please have a try. :)

**Comment by ChrisLLLLL** [comment]
Thank you very much, I tried it and use wireframe dataset, but in "build_homograpy_dataset" I often encounter "valueErroe:could not broardcast input array from shape(480,2 ) into shape (450,2)". Does it have something to do with me not naming the pictures in order?

**Comment by ChrisLLLLL** [comment]
I feel like I want to know what the problem is. I want to know why the processing time of the original picture is 1~2s, but the processing time of wireframe dateset(one picture) is 3.5s.

**Comment by yosungho** [comment]
I found that the hardcoded image_size caused such errors, and I corrected them now. The processing time would be varied on the number of lines. Please try to adjust the max number of sublines to be smaller.

**Comment by ChrisLLLLL** [comment]
> I found that the hardcoded image_size caused such errors, and I corrected them now. The processing time would be varied on the number of lines. Please try to adjust the max number of sublines to be smaller.

I will try it, thank you!

**Comment by ChrisLLLLL** [comment]
Hi. This error is still not resolved. I found out that it was caused by too many matching lines(many-to-many correspondences), Should I raise the threshold“min_overlap_ratio” but will this reduce the training effect? How to let the lines one-to-one?

"Traceback (most recent call last):
  File "dataloaders/build_homography_dataset.py", line 303, in <module>
    main()
  File "dataloaders/build_homography_dataset.py", line 297, in main
    dataset.__getitem__(iter, idx)
  File "dataloaders/build_homography_dataset.py", line 238, in __getitem__
    lmatches_ret[:len(lmatches)] = lmatches
ValueError: could not broadcast input array from shape (504,2) into shape (375,2)
"

**Comment by yosungho** [comment]
Yes, you can raise the min_overlap_ratio to have fewer but more exact GT matches. I think the error occurs because there were too many multiple matching as you mentioned. You can increase the 1.5 to a larger number to resolve it, fixing every other parameter. (the 1.5 represents a margin) For the other options, you can also increase token_distance or min_overlap_ratio to have fewer line correspondences.

**Comment by ChrisLLLLL** [comment]
Thank you. I'll give it a try, hopefully it won't reduce the training accuracy.
